x-app-template: &app_template
  image: wpch/rinha-app:latest
  networks:
    - rinha-net
    - payment-processor
  depends_on:
    - database
    - message_broker
  deploy:
    restart_policy: &default_restart_policy
      condition: on-failure
      delay: 2s
      max_attempts: 10
      window: 5s

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_backend_1
      - app_backend_2
    ports:
      - "9999:9999"
    networks:
      - rinha-net
    deploy:
      restart_policy: *default_restart_policy
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  app_backend_1:
    <<: *app_template
    hostname: app_backend_1
    container_name: app_backend_1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - INSTANCE_ID=APP-BACKEND-1
    deploy:
      restart_policy: *default_restart_policy
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"

  app_backend_2:
    <<: *app_template
    hostname: app_backend_2
    container_name: app_backend_2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - INSTANCE_ID=APP-BACKEND-2
    deploy:
      restart_policy: *default_restart_policy
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"

  database:
    image: postgres:17.0-alpine
    container_name: rinha_db
    environment:
      - POSTGRES_DB=rinha_pagamentos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - rinha_db_data:/var/lib/postgresql/data
    networks:
      - rinha-net
    deploy:
      restart_policy: *default_restart_policy
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  message_broker:
    image: rabbitmq:3-management
    container_name: rinha_rabbit
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rinha-net
    deploy:
      restart_policy: *default_restart_policy
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true

volumes:
  rinha_db_data: