CREATE SCHEMA IF NOT EXISTS sch_rinha;

CREATE TABLE sch_rinha.tb_payments (
   id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   correlation_id  UUID NOT NULL UNIQUE,
   amount          NUMERIC(19, 2) NOT NULL,
   processor_type  VARCHAR(7) NOT NULL,
   processed_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_payments_processed_at ON sch_rinha.tb_payments(processed_at);